spring:
  application:
    name: mutle

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  sql:
    init:
      platform: postgres

jwt:
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000
  secret:

springdoc:
  swagger-ui:
    path: /swagger-ui.html

kakao:
  client-id:
  redirect-url:
  admin-key:

google:
  client-id:
  client-secret:
  redirect-url:
