spring:
  application:
    name: mutle

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  sql:
    init:
      platform: postgres

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-url: ${KAKAO_REDIRECT_URL}
  admin-key:  ${KAKAO_ADMIN_KEY}


google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-url: ${GOOGLE_REDIRECT_URL}

supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_KEY}
  bucket:
    mutle: ${SUPABASE_BUCKET_MUTLE}